from lxml import html
import requests
page0 = requests.get('http://wiki.teamliquid.net/starcraft2/Level_Up_Roma')
page1= requests.get('http://wiki.teamliquid.net/starcraft2/Gauntlet_Season_2_Global_Finals')
page2= requests.get('http://wiki.teamliquid.net/starcraft2/VTL_Allstars')
page3= requests.get('http://wiki.teamliquid.net/starcraft2/Passioncraft_Open_S3')
page4= requests.get('http://wiki.teamliquid.net/starcraft2/GG_year_2016')
page5= requests.get('http://wiki.teamliquid.net/starcraft2/WardiTV_Christmas_Invitational')
page6= requests.get('http://wiki.teamliquid.net/starcraft2/Taco_Cup')
page7= requests.get('http://wiki.teamliquid.net/starcraft2/PSISTORM_Cup_4')
page8= requests.get('http://wiki.teamliquid.net/starcraft2/Topdogs_8')
page9= requests.get('http://wiki.teamliquid.net/starcraft2/StarLine_League_Season_3')
page10= requests.get('http://wiki.teamliquid.net/starcraft2/Leifeng_Cup/158')
page11= requests.get('http://wiki.teamliquid.net/starcraft2/Shang_gan_ling/6')
page12= requests.get('http://wiki.teamliquid.net/starcraft2/Stream.Me_Arena_2')
page13= requests.get('http://wiki.teamliquid.net/starcraft2/EGU_2016')
page14= requests.get('http://wiki.teamliquid.net/starcraft2/Xtreme_Dude_Championship')
page15= requests.get('http://wiki.teamliquid.net/starcraft2/Cheesadelphia_3.5')
page16= requests.get('http://wiki.teamliquid.net/starcraft2/International_Topdogs')
page17= requests.get('http://wiki.teamliquid.net/starcraft2/Shang_gan_ling/5')
page18= requests.get('http://wiki.teamliquid.net/starcraft2/Lima_Gaming_Festival')
page19= requests.get('http://wiki.teamliquid.net/starcraft2/Topdogs_7')
page20= requests.get('http://wiki.teamliquid.net/starcraft2/PSISTORM_Cup_3')
page21= requests.get('http://wiki.teamliquid.net/starcraft2/Topdogs_6')
page22= requests.get('http://wiki.teamliquid.net/starcraft2/ChallengeWars/GGLetsRE')
page23= requests.get('http://wiki.teamliquid.net/starcraft2/Passioncraft_Open')
page24= requests.get('http://wiki.teamliquid.net/starcraft2/Gamer_Sensei_Grand_Slam')
page25= requests.get('http://wiki.teamliquid.net/starcraft2/Shang_gan_ling/4')
page26= requests.get('http://wiki.teamliquid.net/starcraft2/Stream.Me_Arena')
page27= requests.get('http://wiki.teamliquid.net/starcraft2/TAW_Open_EU')
page28= requests.get('http://wiki.teamliquid.net/starcraft2/DSCL_Open_2016')
page29= requests.get('http://wiki.teamliquid.net/starcraft2/Gauntlet_Season_1_Global_Finals')
page30= requests.get('http://wiki.teamliquid.net/starcraft2/Topdogs_5')
page31= requests.get('http://wiki.teamliquid.net/starcraft2/StarLine_1xBet_League_Season_2')
page32= requests.get('http://wiki.teamliquid.net/starcraft2/Shang_gan_ling/3')
page33= requests.get('http://wiki.teamliquid.net/starcraft2/Wardi_Open_1')
page34= requests.get('http://wiki.teamliquid.net/starcraft2/GeForce_Cup_Summer_Edition')
page35= requests.get('http://wiki.teamliquid.net/starcraft2/Leifeng_Cup/150')
page36= requests.get('http://wiki.teamliquid.net/starcraft2/Topdogs_4')
page37= requests.get('http://wiki.teamliquid.net/starcraft2/Valhalla_-_Battle_of_Scandinavia')
page38= requests.get('http://wiki.teamliquid.net/starcraft2/Leifeng_Cup/149')
page39= requests.get('http://wiki.teamliquid.net/starcraft2/World_Electronic_Sports_Games_2016/Asia-Pacific/China/Wuhan')
page40= requests.get('http://wiki.teamliquid.net/starcraft2/World_Electronic_Sports_Games_2016/Asia-Pacific/China/Chengdu')
page41= requests.get('http://wiki.teamliquid.net/starcraft2/Huangshan_Mountain_Open_Cup')
page42= requests.get('http://wiki.teamliquid.net/starcraft2/Shang_gan_ling/1')
page43= requests.get('http://wiki.teamliquid.net/starcraft2/World_Electronic_Sports_Games_2016/Asia-Pacific/China/Nanning')
page44= requests.get('http://wiki.teamliquid.net/starcraft2/World_Electronic_Sports_Games_2016/Asia-Pacific/China/Shenyang')
page45= requests.get('http://wiki.teamliquid.net/starcraft2/Gamercom_2016')
page46= requests.get('http://wiki.teamliquid.net/starcraft2/Topdogs_3')
page47= requests.get('http://wiki.teamliquid.net/starcraft2/Coaching_Zone_1')
page48= requests.get('http://wiki.teamliquid.net/starcraft2/World_Electronic_Sports_Games_2016/Asia-Pacific/China/Beijing')
page49= requests.get('http://wiki.teamliquid.net/starcraft2/PSISTORM_Cup_2')
page50= requests.get('http://wiki.teamliquid.net/starcraft2/The_Gauntlet/Global_showdown')
page51= requests.get('http://wiki.teamliquid.net/starcraft2/World_Electronic_Sports_Games_2016/Asia-Pacific/China/Hefei')
page52= requests.get('http://wiki.teamliquid.net/starcraft2/BaseTradeTV_Map_Test_Tournament')
page53= requests.get('http://wiki.teamliquid.net/starcraft2/Fantasy_Expo_Challenge_Season_3')
page54= requests.get('http://wiki.teamliquid.net/starcraft2/World_Electronic_Sports_Games_2016/Asia-Pacific/China/Qingdao')
page55= requests.get('http://wiki.teamliquid.net/starcraft2/World_Electronic_Sports_Games_2016/Asia-Pacific/China/Changsha')
page56= requests.get('http://wiki.teamliquid.net/starcraft2/Leifeng_Cup/145')
page57= requests.get('http://wiki.teamliquid.net/starcraft2/Ting_of_the_Hill')
page58= requests.get('http://wiki.teamliquid.net/starcraft2/Topdogs_2')
page59= requests.get('http://wiki.teamliquid.net/starcraft2/Torino_Comics_2016')
page60= requests.get('http://wiki.teamliquid.net/starcraft2/Leifeng_Cup/144')
#Start Trees------------------------------------------------------------------
tree0= html.fromstring(page0.content)
tree1= html.fromstring(page1.content)
tree2= html.fromstring(page2.content)
tree3= html.fromstring(page3.content)
tree4= html.fromstring(page4.content)
tree5= html.fromstring(page5.content)
tree6= html.fromstring(page6.content)
tree7= html.fromstring(page7.content)
tree8= html.fromstring(page8.content)
tree9= html.fromstring(page9.content)
tree10= html.fromstring(page10.content)
tree11= html.fromstring(page11.content)
tree12= html.fromstring(page12.content)
tree13= html.fromstring(page13.content)
tree14= html.fromstring(page14.content)
tree15= html.fromstring(page15.content)
tree16= html.fromstring(page16.content)
tree17= html.fromstring(page17.content)
tree18= html.fromstring(page18.content)
tree19= html.fromstring(page19.content)
tree20= html.fromstring(page20.content)
tree21= html.fromstring(page21.content)
tree22= html.fromstring(page22.content)
tree23= html.fromstring(page23.content)
tree24= html.fromstring(page24.content)
tree25= html.fromstring(page25.content)
tree26= html.fromstring(page26.content)
tree27= html.fromstring(page27.content)
tree28= html.fromstring(page28.content)
tree29= html.fromstring(page29.content)
tree30= html.fromstring(page30.content)
tree31= html.fromstring(page31.content)
tree32= html.fromstring(page32.content)
tree33= html.fromstring(page33.content)
tree34= html.fromstring(page34.content)
tree35= html.fromstring(page35.content)
tree36= html.fromstring(page36.content)
tree37= html.fromstring(page37.content)
tree38= html.fromstring(page38.content)
tree39= html.fromstring(page39.content)
tree40= html.fromstring(page40.content)
tree41= html.fromstring(page41.content)
tree42= html.fromstring(page42.content)
tree43= html.fromstring(page43.content)
tree44= html.fromstring(page44.content)
tree45= html.fromstring(page45.content)
tree46= html.fromstring(page46.content)
tree47= html.fromstring(page47.content)
tree48= html.fromstring(page48.content)
tree49= html.fromstring(page49.content)
tree50= html.fromstring(page50.content)
tree51= html.fromstring(page51.content)
tree52= html.fromstring(page52.content)
tree53= html.fromstring(page53.content)
tree54= html.fromstring(page54.content)
tree55= html.fromstring(page55.content)
tree56= html.fromstring(page56.content)
tree57= html.fromstring(page57.content)
tree58= html.fromstring(page58.content)
tree59= html.fromstring(page59.content)
tree60= html.fromstring(page60.content)
#stars players----------------------------------------
players0 = tree0.xpath('//span[@style="vertical-align:-1px;"]/text()')
players1 = tree1.xpath('//span[@style="vertical-align:-1px;"]/text()')
players2 = tree2.xpath('//span[@style="vertical-align:-1px;"]/text()')
players3 = tree3.xpath('//span[@style="vertical-align:-1px;"]/text()')
players4 = tree4.xpath('//span[@style="vertical-align:-1px;"]/text()')
players5 = tree5.xpath('//span[@style="vertical-align:-1px;"]/text()')
players6 = tree6.xpath('//span[@style="vertical-align:-1px;"]/text()')
players7 = tree7.xpath('//span[@style="vertical-align:-1px;"]/text()')
players8 = tree8.xpath('//span[@style="vertical-align:-1px;"]/text()')
players9 = tree9.xpath('//span[@style="vertical-align:-1px;"]/text()')
players10 = tree10.xpath('//span[@style="vertical-align:-1px;"]/text()')
players11 = tree11.xpath('//span[@style="vertical-align:-1px;"]/text()')
players12 = tree12.xpath('//span[@style="vertical-align:-1px;"]/text()')
players13 = tree13.xpath('//span[@style="vertical-align:-1px;"]/text()')
players14 = tree14.xpath('//span[@style="vertical-align:-1px;"]/text()')
players15 = tree15.xpath('//span[@style="vertical-align:-1px;"]/text()')
players16 = tree16.xpath('//span[@style="vertical-align:-1px;"]/text()')
players17 = tree17.xpath('//span[@style="vertical-align:-1px;"]/text()')
players18 = tree18.xpath('//span[@style="vertical-align:-1px;"]/text()')
players19 = tree19.xpath('//span[@style="vertical-align:-1px;"]/text()')
players20 = tree20.xpath('//span[@style="vertical-align:-1px;"]/text()')
players21 = tree21.xpath('//span[@style="vertical-align:-1px;"]/text()')
players22 = tree22.xpath('//span[@style="vertical-align:-1px;"]/text()')
players23 = tree23.xpath('//span[@style="vertical-align:-1px;"]/text()')
players24 = tree24.xpath('//span[@style="vertical-align:-1px;"]/text()')
players25 = tree25.xpath('//span[@style="vertical-align:-1px;"]/text()')
players26 = tree26.xpath('//span[@style="vertical-align:-1px;"]/text()')
players27 = tree27.xpath('//span[@style="vertical-align:-1px;"]/text()')
players28 = tree28.xpath('//span[@style="vertical-align:-1px;"]/text()')
players29 = tree29.xpath('//span[@style="vertical-align:-1px;"]/text()')
players30 = tree30.xpath('//span[@style="vertical-align:-1px;"]/text()')
players31 = tree31.xpath('//span[@style="vertical-align:-1px;"]/text()')
players32 = tree32.xpath('//span[@style="vertical-align:-1px;"]/text()')
players33 = tree33.xpath('//span[@style="vertical-align:-1px;"]/text()')
players34 = tree34.xpath('//span[@style="vertical-align:-1px;"]/text()')
players35 = tree35.xpath('//span[@style="vertical-align:-1px;"]/text()')
players36 = tree36.xpath('//span[@style="vertical-align:-1px;"]/text()')
players37 = tree37.xpath('//span[@style="vertical-align:-1px;"]/text()')
players38 = tree38.xpath('//span[@style="vertical-align:-1px;"]/text()')
players39 = tree39.xpath('//span[@style="vertical-align:-1px;"]/text()')
players40 = tree40.xpath('//span[@style="vertical-align:-1px;"]/text()')
players41 = tree41.xpath('//span[@style="vertical-align:-1px;"]/text()')
players42 = tree42.xpath('//span[@style="vertical-align:-1px;"]/text()')
players43 = tree43.xpath('//span[@style="vertical-align:-1px;"]/text()')
players44 = tree44.xpath('//span[@style="vertical-align:-1px;"]/text()')
players45 = tree45.xpath('//span[@style="vertical-align:-1px;"]/text()')
players46 = tree46.xpath('//span[@style="vertical-align:-1px;"]/text()')
players47 = tree47.xpath('//span[@style="vertical-align:-1px;"]/text()')
players48 = tree48.xpath('//span[@style="vertical-align:-1px;"]/text()')
players49 = tree49.xpath('//span[@style="vertical-align:-1px;"]/text()')
players50 = tree50.xpath('//span[@style="vertical-align:-1px;"]/text()')
players51 = tree51.xpath('//span[@style="vertical-align:-1px;"]/text()')
players52 = tree52.xpath('//span[@style="vertical-align:-1px;"]/text()')
players53 = tree53.xpath('//span[@style="vertical-align:-1px;"]/text()')
players54 = tree54.xpath('//span[@style="vertical-align:-1px;"]/text()')
players55 = tree55.xpath('//span[@style="vertical-align:-1px;"]/text()')
players56 = tree56.xpath('//span[@style="vertical-align:-1px;"]/text()')
players57 = tree57.xpath('//span[@style="vertical-align:-1px;"]/text()')
players58 = tree58.xpath('//span[@style="vertical-align:-1px;"]/text()')
players59 = tree59.xpath('//span[@style="vertical-align:-1px;"]/text()')
players60 = tree60.xpath('//span[@style="vertical-align:-1px;"]/text()')
players=[players0,players8,players1,players2,players3,players4,players5,players6,players7,players9,players10,players11,players12,players13,players14,players15,players16,players17,players18,players19,players20,players21,players22,players23,players24,players25,players26,players27,players28,players29,players30,players31,players32,players33,players34,players35,players36,players37,players38,players39,players40,players41,players42,players43,players44,players45,players46,players47,players48,players49,players50,players51,players52,players53,players54,players55,players56,players57,players58,players59,players60]



scores0= tree0.xpath('//div[@style="width:21px"]/text()')
scores1= tree1.xpath('//div[@style="width:21px"]/text()')
scores2= tree2.xpath('//div[@style="width:21px"]/text()')
scores3= tree3.xpath('//div[@style="width:21px"]/text()')
scores4= tree4.xpath('//div[@style="width:21px"]/text()')
scores5= tree5.xpath('//div[@style="width:21px"]/text()')	
scores6= tree6.xpath('//div[@style="width:21px"]/text()')
scores7= tree7.xpath('//div[@style="width:21px"]/text()')
scores8= tree8.xpath('//div[@style="width:21px"]/text()')
scores9= tree9.xpath('//div[@style="width:21px"]/text()')
scores10= tree10.xpath('//div[@style="width:21px"]/text()')
scores11= tree11.xpath('//div[@style="width:21px"]/text()')
scores12= tree12.xpath('//div[@style="width:21px"]/text()')
scores13= tree13.xpath('//div[@style="width:21px"]/text()')
scores14= tree14.xpath('//div[@style="width:21px"]/text()')
scores15= tree15.xpath('//div[@style="width:21px"]/text()')
scores16= tree16.xpath('//div[@style="width:21px"]/text()')
scores17= tree17.xpath('//div[@style="width:21px"]/text()')
scores18= tree18.xpath('//div[@style="width:21px"]/text()')
scores19= tree19.xpath('//div[@style="width:21px"]/text()')
scores20= tree20.xpath('//div[@style="width:21px"]/text()')
scores21= tree21.xpath('//div[@style="width:21px"]/text()')
scores22= tree22.xpath('//div[@style="width:21px"]/text()')
scores23= tree23.xpath('//div[@style="width:21px"]/text()')
scores24= tree24.xpath('//div[@style="width:21px"]/text()')
scores25= tree25.xpath('//div[@style="width:21px"]/text()')
scores26= tree26.xpath('//div[@style="width:21px"]/text()')
scores27= tree27.xpath('//div[@style="width:21px"]/text()')
scores28= tree28.xpath('//div[@style="width:21px"]/text()')
scores29= tree29.xpath('//div[@style="width:21px"]/text()')
scores30= tree30.xpath('//div[@style="width:21px"]/text()')
scores31= tree31.xpath('//div[@style="width:21px"]/text()')
scores32= tree32.xpath('//div[@style="width:21px"]/text()')
scores33= tree33.xpath('//div[@style="width:21px"]/text()')
scores34= tree34.xpath('//div[@style="width:21px"]/text()')
scores35= tree35.xpath('//div[@style="width:21px"]/text()')
scores36= tree36.xpath('//div[@style="width:21px"]/text()')
scores37= tree37.xpath('//div[@style="width:21px"]/text()')
scores38= tree38.xpath('//div[@style="width:21px"]/text()')
scores39= tree39.xpath('//div[@style="width:21px"]/text()')
scores40= tree40.xpath('//div[@style="width:21px"]/text()')
scores41= tree41.xpath('//div[@style="width:21px"]/text()')
scores42= tree42.xpath('//div[@style="width:21px"]/text()')
scores43= tree43.xpath('//div[@style="width:21px"]/text()')
scores44= tree44.xpath('//div[@style="width:21px"]/text()')
scores45= tree45.xpath('//div[@style="width:21px"]/text()')
scores46= tree46.xpath('//div[@style="width:21px"]/text()')
scores47= tree47.xpath('//div[@style="width:21px"]/text()')
scores48= tree48.xpath('//div[@style="width:21px"]/text()')
scores49= tree49.xpath('//div[@style="width:21px"]/text()')
scores50= tree50.xpath('//div[@style="width:21px"]/text()')
scores51= tree51.xpath('//div[@style="width:21px"]/text()')
scores52= tree52.xpath('//div[@style="width:21px"]/text()')
scores53= tree53.xpath('//div[@style="width:21px"]/text()')
scores54= tree54.xpath('//div[@style="width:21px"]/text()')
scores55= tree55.xpath('//div[@style="width:21px"]/text()')
scores56= tree56.xpath('//div[@style="width:21px"]/text()')
scores57= tree57.xpath('//div[@style="width:21px"]/text()')
scores58= tree58.xpath('//div[@style="width:21px"]/text()')
scores59= tree59.xpath('//div[@style="width:21px"]/text()')
scores60= tree60.xpath('//div[@style="width:21px"]/text()')
score_list=[scores0,scores1,scores2,scores3,scores4,scores5,scores6,scores7,scores8,scores9,scores10,scores11,scores12,scores13,scores14,scores15,scores16,scores17,scores18,scores19,scores20,scores21,scores22,scores23,scores24,scores25,scores26,scores27,scores28,scores29,scores30,scores31,scores32,scores33,scores34,scores35,scores36,scores37,scores38,scores39,scores40,scores41,scores42,scores43,scores44,scores45,scores46,scores47,scores48,scores49,scores50,scores51,scores52,scores53,scores54,scores55,scores56,scores57,scores58,scores59,scores60]






player_list=[]
for i in range (0, len(players)):
	for t in range(0, len(players[i])):
		player_list.append(players[i][t])

player_scores=[]
for i in range (0, len(score_list)):
	for t in range(0, len(score_list[i])):
		player_scores.append(score_list[i][t])
		
print player_list

print player_scores
print len(player_scores)
print len(player_list)

print players0
print scores0
print len(players0)
print len(scores0)
###left off at http://wiki.teamliquid.net/starcraft2/Gamer_Sensei_Grand_Slam

